FROM tensorflow/tensorflow:1.14.0-py3
# copy the repository form the previous image

WORKDIR /opt/ml/code/

RUN apt-get update && apt-get install -y \
  git protobuf-compiler curl unzip

RUN curl -OL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
RUN unzip protoc-3.2.0-linux-x86_64.zip -d protoc3
RUN mv protoc3/bin/* /usr/local/bin/
RUN mv protoc3/include/* /usr/local/include/

RUN pip install Cython contextlib2 pillow lxml jupyter matplotlib -i http://ftp.daumkakao.com/pypi/simple --trusted-host ftp.daumkakao.com

# copy object_detection, slim repo
COPY object_detection object_detection
COPY slim slim
COPY setup.py setup.py

RUN protoc object_detection/protos/*.proto --python_out=.
RUN echo "export PYTHONPATH=${PYTHONPATH}:`pwd`:`pwd`/slim" >> ~/.bashrc
RUN python setup.py install

# coco api install
RUN pip install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI