FROM ubuntu:16.04 as intermediate

# install git
RUN apt update
RUN apt install -y git

# add credentials on build
ARG SSH_PRIVATE_KEY
RUN mkdir /root/.ssh/
RUN echo "${SSH_PRIVATE_KEY}" > /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa

# # make sure your domain is accepted
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

RUN git clone git@github.com:ssoonan/tensorflow_object_detection.git

##----------- github ssh part end----------

FROM tensorflow/tensorflow:1.12.0-py3
# copy the repository form the previous image
COPY --from=intermediate /tensorflow_object_detection /opt/ml/code

RUN apt-get update && apt-get install -y \
  git protobuf-compiler

RUN curl -OL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
RUN unzip protoc-3.2.0-linux-x86_64.zip -d protoc3
RUN mv protoc3/bin/* /usr/local/bin/
RUN mv protoc3/include/* /usr/local/include/

WORKDIR /opt/ml/code/

RUN pip install --user Cython contextlib2 pillow lxml jupyter matplotlib

RUN protoc object_detection/protos/*.proto --python_out=.
RUN echo "export PYTHONPATH=${PYTHONPATH}:`pwd`:`pwd`/slim" >> ~/.bashrc
RUN python setup.py install

# coco api install
RUN git clone https://github.com/cocodataset/cocoapi.git
RUN cd cocoapi/PythonAPI &&  make && cp -r pycocotools /opt/ml/code